### ISSUE TITLE
Demo Site Offline?

### ISSUE THREAD

**Issue by Lvl4Sword** [chriskok/AnimeRec#1]
http://3.131.210.47:5000/ fails and has failed for some time now.

**Comment by chriskok** [comment]
Hi! You're right, we've taken it down because we're switching over to using REACT and the free AWS EC2 instance it was running on just couldn't support it any longer. We're taking some time to decide on a paid option as well as how often the site will be up. Will let you know when it's back! Sorry for any inconvenience.

**Comment by Lvl4Sword** [comment]
@chriskok I take it https://www.randomanime.org/anime-like/ is the correct URL for this now?

**Comment by chriskok** [comment]
@Lvl4Sword Yeap! That's where it's hosted now - we've partnered with Kyle from RandomAnime! Thanks for following up on it.
